### ISSUE TITLE
Using this as an OPRF

### ISSUE THREAD

**Issue by sourabhmarathe** [encryptogroup/OTExtension#14]
I was wondering if it is possible to use this as a basis for creating an OPRF. Additionally, if it is possible, would I be able to create my own keys for a given sender/receiver? Also, would I be able to send any input to a given instance of the OPRF?

**Comment by thomaschneider** [comment]
You might want to consider this implementation of an OPRF based on OT extension: https://github.com/osu-crypto/BaRK-OPRF

—-

**Comment by sourabhmarathe** [comment]
Thanks for getting back. I'll check it out.
