### ISSUE TITLE
Inconsistent interface of PVWDDH::Receiver

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/OTExtension#17]
[`PVWDDH::Receiver`](https://github.com/encryptogroup/OTExtension/blob/835b532ac082ecac462333fb693d0f637d15daec/ot/pvwddh.h#L22) takes a reference to a `CBitVector` while the base class [`BaseOT`](https://github.com/encryptogroup/OTExtension/blob/835b532ac082ecac462333fb693d0f637d15daec/ot/baseOT.h#L35) and all other derived subclasses specify a pointer instead. This should probably be adjusted.

Clang warning:
```
In file included from pvwddh.cpp:1:
./pvwddh.h:22:7: warning: 'PVWDDH::Receiver' hides overloaded virtual function [-Woverloaded-virtual]
        void Receiver(uint32_t nSndVals, uint32_t nOTs, CBitVector& choices, channel* chan, BYTE* ret);
             ^
./baseOT.h:35:15: note: hidden overloaded virtual function 'BaseOT::Receiver' declared here: type mismatch at 3rd
      parameter ('CBitVector *' vs 'CBitVector &')
        virtual void Receiver(uint32_t nSndVals, uint32_t uint32_t, CBitVector* choices, channel* chan, uint8_t...
                     ^
```

**Comment by dd23** [comment]
Thanks for spotting this.
Fixed in 306201e765afaef703bc9079a0097e83b644abfb
