### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by YaLunDong** [encryptogroup/OTExtension#29]
Hi,when I run cmake .. in build,I met the following problem,
`CMake Error at CMakeLists.txt:22 (add_library):
  Target "otextension" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:22 (add_library):
  Target "otextension" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at mains/CMakeLists.txt:4 (add_executable):
  Target "otmain" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at mains/CMakeLists.txt:4 (add_executable):
  Target "otmain" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at mains/CMakeLists.txt:1 (add_executable):
  Target "test" links to target "Boost::system" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at mains/CMakeLists.txt:1 (add_executable):
  Target "test" links to target "Boost::thread" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
`
cmake can find boost,soI am confused,could you give me some advice?

**Comment by dd23** [comment]
Is your boost version 1.66 or newer?

**Comment by YaLunDong** [comment]
yes，my boost is version 1.69

**Comment by YaLunDong** [comment]
> Is your boost version 1.66 or newer?

yes,my boost is version 1.69

**Comment by dd23** [comment]
Can you please post the full output of `cmake ..`?
What happens if you try to build a new clone of the repo?
Which OS are you on?

**Comment by YaLunDong** [comment]
> Can you please post the full output of `cmake ..`?
> What happens if you try to build a new clone of the repo?
> Which OS are you on?

when I run `cmake ..`,it outputs as follows:
`-- Found ENCRYPTO_utils
-- Boost version: 1.69.0
-- Configuring done
CMake Error at CMakeLists.txt:22 (add_library):
  Target "otextension" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:22 (add_library):
  Target "otextension" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at mains/CMakeLists.txt:4 (add_executable):
  Target "otmain" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at mains/CMakeLists.txt:4 (add_executable):
  Target "otmain" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at mains/CMakeLists.txt:1 (add_executable):
  Target "test" links to target "Boost::system" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at mains/CMakeLists.txt:1 (add_executable):
  Target "test" links to target "Boost::thread" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/dy/OTExtension/build`
and my OS is Ubuntu 18.04

**Comment by YaLunDong** [comment]
> Can you please post the full output of `cmake ..`?
> What happens if you try to build a new clone of the repo?
> Which OS are you on?

and more info. about boost
![Screenshot from 2019-03-14 21-31-07](https://user-images.githubusercontent.com/23722139/54360792-9b8e0b80-46a0-11e9-8bf6-4d3d2e3b911e.png)

**Comment by dd23** [comment]
You might be running an older version of cmake, which needs some adjustments. Or you could update to a newer cmake version, if that's the problem.

Have a look here, where we had similar issues:
https://github.com/encryptogroup/ABY/issues/115

**Comment by YaLunDong** [comment]
> You might be running an older version of cmake, which needs some adjustments. Or you could update to a newer cmake version, if that's the problem.
> 
> Have a look here, where we had similar issues:
> [encryptogroup/ABY#115](https://github.com/encryptogroup/ABY/issues/115)

Thank you very much for your help,it seems to be my problem.But my cmake is v3.14.0,I get the same problem as usual,which is a sad story.

**Comment by WhiteCatFly** [comment]
I get the same problem.My cmake is also v3.14.0 and Boost is v1.69. Maybe you can change your Boost to v1.68 and cmake to v3.13

**Comment by lenerd** [comment]
I successfully use cmake v3.14.0 and Boost v1.69 and upon calling CMake I get:
```
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
```
Did you install all parts of the Boost libraries? Sometimes the distribution split Boost into several packages, e.g. Ubuntu. Which operating system do you use?

**Comment by WhiteCatFly** [comment]
Do you use apt to manage packages on Ubuntu? If yes, can I take a look at your apt source list file at `/etc/apt/sources.list`

**Comment by lenerd** [comment]
I am running Arch Linux. How and where did you install Boost and CMake?

**Comment by WhiteCatFly** [comment]
I used source code of Boost download from [boost.org](boost.org) to install Boost at `/usr/local` and install the release of Cmake from GitHub at `~/Downloads`

**Comment by YaLunDong** [comment]
> I successfully use cmake v3.14.0 and Boost v1.69 and upon calling CMake I get:
> 
> ```
> -- Boost version: 1.69.0
> -- Found the following Boost libraries:
> --   system
> --   thread
> --   chrono
> --   date_time
> --   atomic
> ```
> Did you install all parts of the Boost libraries? Sometimes the distribution split Boost into several packages, e.g. Ubuntu. Which operating system do you use?
My OS is Ubuntu, and when I add find_package(Boost 1.69.0 COMPONENTS system thread filesystem REQUIRED) to CMakeList.txt , I can find the above boost libraries as well . And I compiled OTExtension successfully.
![Screenshot from 2019-03-19 10-00-58](https://user-images.githubusercontent.com/23722139/54575230-40f10880-4a2e-11e9-8792-088c6778408f.png)
However,when I built the examples in mains, it reported some errors as blow.
![Screenshot from 2019-03-19 10-04-08](https://user-images.githubusercontent.com/23722139/54575266-6251f480-4a2e-11e9-8efe-0e777431f402.png)

Thank you for your kindness.

**Comment by YaLunDong** [comment]
> I used source code of Boost download from [boost.org](boost.org) to install Boost at `/usr/local` and install the release of Cmake from GitHub at `~/Downloads`

Boost is at '/usr/include' and cmake is  at '/usr/local/bin'

**Comment by YaLunDong** [comment]
> Do you use apt to manage packages on Ubuntu? If yes, can I take a look at your apt source list file at `/etc/apt/sources.list`

my sources.list is as follows:
"# deb cdrom:[Ubuntu 18.04.1 LTS _Bionic Beaver_ - Release amd64 (20180725)]/ bionic main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic universe
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic universe
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates universe
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
# deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse
deb http://us.archive.ubuntu.com/ubuntu saucy main universe
"

**Comment by YaLunDong** [comment]
> Do you use apt to manage packages on Ubuntu? If yes, can I take a look at your apt source list file at `/etc/apt/sources.list`

It is 
`# deb cdrom:[Ubuntu 18.04.1 LTS _Bionic Beaver_ - Release amd64 (20180725)]/ bionic main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic universe
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic universe
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates universe
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://cn.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
# deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse
deb http://us.archive.ubuntu.com/ubuntu saucy main universe
`

**Comment by dd23** [comment]
I'm not sure if this is all to the isse, but running `cmake ..` from `OTExtension/mains/build` does not touch the CMakeLists.txt in the root directory ot OTExtension.

If you look at the README, you should make a directory called `build` and run `cmake ..` from there (`OTExtension/build`).

Also, can you please try to clone a fresh and unmodified version of OTExtension and try tu build that one?

**Comment by YaLunDong** [comment]
> I'm not sure if this is all to the isse, but running `cmake ..` from `OTExtension/mains/build` does not touch the CMakeLists.txt in the root directory ot OTExtension.
> 
> If you look at the README, you should make a directory called `build` and run `cmake ..` from there (`OTExtension/build`).
> 
> Also, can you please try to clone a fresh and unmodified version of OTExtension and try tu build that one?

Thank you for your help, I will take your advice.

**Comment by dd23** [comment]
We have a [similar issue with ABY](https://github.com/encryptogroup/ABY/issues/133), which internally uses OTExtesion.

I tried to recreate the problem and came up with something that worked for me on Ubuntu 18.04. Maybe that helps you as well:

I installed CMake 3.14 with the following commands (which we also use for TravisCI):
```
mkdir $HOME/prefix
export PATH="$HOME/prefix/bin:$PATH"
wget https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh -O cmake_install.sh
chmod +x cmake_install.sh
./cmake_install.sh --prefix=$HOME/prefix --exclude-subdir --skip-license
```

I installed boost 1.68 as follows:
```
add-apt-repository ppa:mhier/libboost-latest
apt install libboost1.68-dev
```

Also, make sure to use g++8, if that is not your default:
```
CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake .. -DABY_BUILD_EXE=On
```

**Comment by YaLunDong** [comment]
> We have a [similar issue with ABY](https://github.com/encryptogroup/ABY/issues/133), which internally uses OTExtesion.
> 
> I tried to recreate the problem and came up with something that worked for me on Ubuntu 18.04. Maybe that helps you as well:
> 
> I installed CMake 3.14 with the following commands (which we also use for TravisCI):
> 
> ```
> mkdir $HOME/prefix
> export PATH="$HOME/prefix/bin:$PATH"
> wget https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh -O cmake_install.sh
> chmod +x cmake_install.sh
> ./cmake_install.sh --prefix=$HOME/prefix --exclude-subdir --skip-license
> ```
> I installed boost 1.68 as follows:
> 
> ```
> add-apt-repository ppa:mhier/libboost-latest
> apt install libboost1.68-dev
> ```
> Also, make sure to use g++8, if that is not your default:
> 
> ```
> CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake .. -DABY_BUILD_EXE=On
> ```

Thank you very much,I will try it.Thank you.

**Comment by ToraNova** [comment]
Hi, just wanna confirm that adding the following line `find_package(Boost 1.69.0 COMPONENTS system thread filesystem REQUIRED)` in the CMakeLists.txt solves the problem for me as well.

**Comment by dd23** [comment]
We have a [very similar line in the CMakeLists.txt of Encrypto_utils](https://github.com/encryptogroup/ENCRYPTO_utils/blob/a596166d9ebdc506d1ecb2394fac5ee5d598297b/CMakeLists.txt#L15).
As ENCRYPTO_utils is imported as git submodule, I would expect that this should already cause an error when building.

Note also, that boost's `filesystem` should not be required. We're only using `std::filesystem` in ABY, not in OTExtension.

Can this issue be closed?

**Comment by YaLunDong** [comment]
Yes, I have solved this problems. Thank you very much
发送自 Windows 10 版邮件应用

发件人: Daniel D.
发送时间: 2019年8月22日 21:33
收件人: encryptogroup/OTExtension
抄送: Ye D.; Author
主题: Re: [encryptogroup/OTExtension] cmake error (#29)

We have a very similar line in the CMakeLists.txt of Encrypto_utils.
As ENCRYPTO_utils is imported as git submodule, I would expect that this should already cause an error when building.
Note also, that boost's filesystem should not be required. We're only using std::filesystem in ABY, not in OTExtension.
Can this issue be closed?

**Comment by mialuyao** [comment]
> Hi, just wanna confirm that adding the following line `find_package(Boost 1.69.0 COMPONENTS system thread filesystem REQUIRED)` in the CMakeLists.txt solves the problem for me as well.

I have added this line in the CMakeLists.txt， but this problem remains.
