### ISSUE TITLE
No automake?

### ISSUE THREAD

**Issue by mmaker** [encryptogroup/OTExtension#3]
hey, thanks for opensourcing an implementation of  IKNP and KK13. 
I accidentaly opened ```OTExtension/util/Miracl/linux```, and my eyes were bleeding. Would you guys be interested in a patch to migrate to automake/autoconf for building the whole library for OT extension?

**Comment by MichaelZohner** [comment]
Hi Michele, thanks for your comment. 
Please note that Miracl is an external library which is not maintained by us. I had planned to outsource it as an external project within GIT and to add the necessary commands for building it to the Makefile but probably had forgotten about it. I will add the changes within the next days. 
Best, 
Michael

**Comment by MichaelZohner** [comment]
I outsourced Miracl as a submodule but did not change its internal structure, since only the miracl.a file is needed.
