### ISSUE TITLE
Unable to compile with missing boost/asio/io_context.hpp ?

### ISSUE THREAD

**Issue by ToraNova** [encryptogroup/OTExtension#30]
Dear developers,

I am having trouble compiling the OTExtension library on ubuntu 18.04. After following the steps in the guide, I found myself stuck due to g++ compiler unable to locate the following header files
`fatal error: boost/asio/io_context.hpp: No such file or directory #include <boost/asio/io_context.hpp>
`
I have the libboost-all-dev library installed using apt-get and is able to locate the asio include folder under /usr/include/boost/asio. However, doing a find /usr | grep asio/io_context returns nothing.

How do I mitigate this issue ?

**Comment by ToraNova** [comment]
The following is the make error message that I got.
`[ 61%] Built target miracl
[ 62%] Building CXX object extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/ENCRYPTO_utils/socket.cpp.o
/home/cjason/Desktop/secure-dist-computing/OTExtension/extern/ENCRYPTO_utils/src/ENCRYPTO_utils/socket.cpp:28:10: fatal error: boost/asio/io_context.hpp: No such file or directory
 #include <boost/asio/io_context.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/build.make:283: recipe for target 'extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/ENCRYPTO_utils/socket.cpp.o' failed
make[2]: *** [extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/ENCRYPTO_utils/socket.cpp.o] Error 1
CMakeFiles/Makefile2:204: recipe for target 'extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/all' failed
make[1]: *** [extern/ENCRYPTO_utils/src/CMakeFiles/encrypto_utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by lenerd** [comment]
Hi,
we need Boost to be at least version v1.66 as they changed some interfaces. I think Ubuntu 18.04 ships only v1.65.

**Comment by ToraNova** [comment]
Thanks ! now able to proceed with the compilation.
