### ISSUE TITLE
problem in making code

### ISSUE THREAD

**Issue by fatemehajikarami** [encryptogroup/OTExtension#4]
Hi
I am trying to make, but I get these errors:

In file included from crypto.cpp:8:0:
crypto.h:45:14: error: field ‘aes_key’ has incomplete type ‘AES_KEY_CTX {aka evp_cipher_ctx_st}’
  AES_KEY_CTX aes_key;
              ^
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from crypto.h:11,
                 from crypto.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘AES_KEY_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
In file included from crypto.cpp:8:0:
crypto.h:107:14: error: field ‘aes_hash_key’ has incomplete type ‘AES_KEY_CTX {aka evp_cipher_ctx_st}’
  AES_KEY_CTX aes_hash_key;
              ^
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from crypto.h:11,
                 from crypto.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘AES_KEY_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
In file included from crypto.cpp:8:0:
crypto.h:108:14: error: field ‘aes_enc_key’ has incomplete type ‘AES_KEY_CTX {aka evp_cipher_ctx_st}’
  AES_KEY_CTX aes_enc_key;
              ^
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from crypto.h:11,
                 from crypto.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘AES_KEY_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
In file included from crypto.cpp:8:0:
crypto.h:109:14: error: field ‘aes_dec_key’ has incomplete type ‘AES_KEY_CTX {aka evp_cipher_ctx_st}’
  AES_KEY_CTX aes_dec_key;
              ^
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from crypto.h:11,
                 from crypto.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘AES_KEY_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
Makefile:63: recipe for target 'util/crypto/*.o' failed
make: *** [util/crypto/*.o] Error 1

How can I solve this?

**Comment by MichaelZohner** [comment]
EVP_CIPHER_CTX was made opaque in OpenSSL 1.1.0. 
The latest commits should fix this and provide backward compatibility.
